name: Docker-Login-Build-Push

on: 
  push:
    branches: [main]
  
  workflow_dispatch:

env:
  DOCKER_HUB_REPO: 3120-proj4
  
jobs:
  build_and_push:
    name: Build a docker image and push it to DockerHub
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repo to runner
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER }}
      
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:latest
